/**
 * Notification trigger logic — pure functions for determining when and how
 * to fire local notifications for remote task events.
 *
 * Security: Notification bodies are always generic — never include task titles,
 * room names, or user data.
 */

import type { TaskEvent, Task } from '$lib/tasks/types';

/**
 * Determines if a remote task event should trigger a notification.
 *
 * Returns true when:
 * - task_assigned: task's new assignee is myIdentityKey AND actor is NOT me
 * - task_status_changed: task.assignee is myIdentityKey AND actor is NOT me
 *
 * Returns false when:
 * - Event was generated by me (actorId === myIdentityKey)
 * - Tab is focused (document.visibilityState === 'visible')
 * - Notifications not enabled
 * - Ephemeral room
 */
export function shouldNotifyForEvent(
	event: TaskEvent,
	myIdentityKey: string,
	tasks: Task[],
	notificationsEnabled: boolean,
	isEphemeral: boolean,
): boolean {
	// Don't notify for own actions
	if (event.actorId === myIdentityKey) return false;

	// Don't notify if disabled or ephemeral
	if (!notificationsEnabled || isEphemeral) return false;

	// Don't notify when tab is focused
	if (typeof document !== 'undefined' && document.visibilityState === 'visible') return false;

	if (event.type === 'task_assigned') {
		// Notify when a task is assigned TO me
		const task = tasks.find((t) => t.id === event.taskId);
		return task?.assignee === myIdentityKey;
	}

	if (event.type === 'task_status_changed') {
		// Notify when status changes on a task assigned to me
		const task = tasks.find((t) => t.id === event.taskId);
		return task?.assignee === myIdentityKey;
	}

	return false;
}

/**
 * Returns a generic notification payload — NEVER includes task content.
 */
export function getNotificationPayload(event: TaskEvent): { title: string; body: string; tag: string } {
	return {
		title: 'Weave',
		body: 'You have a new notification — open Weave to view details',
		tag: `weave-${event.type}-${event.taskId}`,
	};
}

/**
 * Posts a notification request to the service worker.
 * The SW enforces quiet hours before showing.
 */
export function postNotifyToSW(
	payload: { title: string; body: string; tag: string },
	roomId: string,
): void {
	if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;

	const controller = navigator.serviceWorker.controller;
	if (!controller) return;

	try {
		controller.postMessage({
			type: 'NOTIFY',
			title: payload.title,
			body: payload.body,
			tag: payload.tag,
			roomId,
		});
	} catch {
		// Silent failure
	}
}

/**
 * Posts updated notification preferences to the service worker.
 */
export function postPrefsToSW(prefs: {
	roomId: string;
	enabled: boolean;
	quietStart: string;
	quietEnd: string;
}): void {
	if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;

	const controller = navigator.serviceWorker.controller;
	if (!controller) return;

	try {
		controller.postMessage({
			type: 'UPDATE_NOTIFICATION_PREFS',
			prefs,
		});
	} catch {
		// Silent failure
	}
}
